[package]
name = "web-client"
version = "0.1.0"
authors = ["csdietz@google.com"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
gloo-utils = "0.2.0"
log = "0.4.28"
serde_json = "1.0.145"
wasm-bindgen = "0.2.105"
wasm-logger = "0.2.0"
web-common = { path = "../web-common" }
web-sys = "0.3.82"
yew = { version = "0.21", features = ["csr"] }
yew-hooks = "0.3.4"

[lints]
clippy.mod-module-files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit-arg = "allow"
rust.unused-crate-dependencies = "warn"
