version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/crates/**/*"
      - "/examples/rust/**/*"
    schedule: { interval: "monthly" }
    groups:
      all:
        applies-to: security-updates
        patterns: ["*"]
    labels: []
    # Version updates are done with ./scripts/upgrade.sh.
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      # TODO(https://github.com/dependabot/dependabot-core/issues/6345): Use glob.
      - "/.github/actions/ci-checks"
      - "/.github/actions/ci-footprint"
    schedule: { interval: "monthly" }
    groups: { all: { patterns: ["*"] } }
    labels: []
