[toolchain]
channel = "nightly-2024-10-29"
components = ["clippy", "llvm-tools", "miri", "rust-src", "rustfmt"]
targets = [
  "i686-unknown-linux-gnu",
  "riscv32imc-unknown-none-elf",
  "thumbv7em-none-eabi",
  "wasm32-unknown-unknown",
  "x86_64-unknown-linux-gnu",
]
