[package]
name = "ec_test"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
wasefire = { path = "../../../crates/prelude" }
wasefire-stub = { path = "../../../crates/stub", optional = true }

[features]
test = ["dep:wasefire-stub", "wasefire/test"]
