[package]
name = "part-7-sol"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
interface = { path = "../interface" }
wasefire = { path = "../../../../crates/prelude" }

[features]
usb = [] # Use USB serial instead of UART.
