[package]
name = "web-common"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.107"
